
import React, { useState, useEffect, useRef } from 'react';
import ReactMarkdown from 'react-markdown';
import { ItineraryResult, UserPreferences, ItineraryStep } from '../types';
import { TRANSLATIONS, RECOMMENDED_RESTAURANTS } from '../constants';
import ItineraryStepCard from './ItineraryStepCard';
import { generateStepImage, generateStepInstructions, getNearbyAttractions } from '../services/geminiService';

interface ResultDisplayProps {
  result: ItineraryResult;
  preferences: UserPreferences;
  onReset: () => void;
  onSave?: () => boolean; 
}

// Helper to parse time strings into comparable minutes from midnight
const parseTime = (timeStr: string): number => {
    if (!timeStr) return 9999;
    const lower = timeStr.toLowerCase().trim();
    
    // Check for HH:MM format first (e.g. 09:00, 9:30, 14:00, 9h30)
    const timeMatch = lower.match(/(\d{1,2})[:h.](\d{2})/);
    if (timeMatch) {
        let h = parseInt(timeMatch[1]);
        const m = parseInt(timeMatch[2]);
        if (lower.includes('pm') && h < 12) h += 12;
        if (lower.includes('am') && h === 12) h = 0;
        return h * 60 + m;
    }

    // Check for keywords
    if (lower.includes('esmorzar') || lower.includes('desayuno') || lower.includes('breakfast')) return 8 * 60;
    if (lower.includes('morning') || lower.includes('matí') || lower.includes('mañana')) return 9 * 60;
    if (lower.includes('migdia') || lower.includes('mediodía') || lower.includes('noon') || lower.includes('lunch') || lower.includes('dinar') || lower.includes('comida')) return 13 * 60 + 30;
    if (lower.includes('afternoon') || lower.includes('tarda') || lower.includes('tarde')) return 16 * 60;
    if (lower.includes('vespre') || lower.includes('noche') || lower.includes('evening') || lower.includes('sopar') || lower.includes('cena') || lower.includes('dinner')) return 20 * 60 + 30;
    if (lower.includes('night') || lower.includes('nit')) return 22 * 60;
    
    return 9999;
};

const ResultDisplay: React.FC<ResultDisplayProps> = ({ result, preferences, onReset, onSave }) => {
  
  const [steps, setSteps] = useState<ItineraryStep[]>([]);
  const [activeDay, setActiveDay] = useState<string>("");
  const [showToast, setShowToast] = useState<{msg: string, type: 'success' | 'info'} | null>(null);
  const [isBookingsOpen, setIsBookingsOpen] = useState(false);
  const [isDeltaInfoOpen, setIsDeltaInfoOpen] = useState(false);
  const [isTaxiInfoOpen, setIsTaxiInfoOpen] = useState(false);
  const [isRestaurantInfoOpen, setIsRestaurantInfoOpen] = useState(false);
  const [selectedBookingStep, setSelectedBookingStep] = useState<ItineraryStep | null>(null);
  const [ratings, setRatings] = useState<Record<string, number>>({});
  
  const autoGeneratedRef = useRef<Set<string>>(new Set());
  const webSources = result.sources.filter(s => s.type === 'web');
  const t = TRANSLATIONS[preferences.language];

  useEffect(() => {
    if (result.steps && result.steps.length > 0) {
      // Sort steps chronologically
      const sortedSteps = [...result.steps].sort((a, b) => {
          // First by Day
          const dayA = parseInt(a.day) || 999;
          const dayB = parseInt(b.day) || 999;
          if (dayA !== dayB) return dayA - dayB;
          
          // Then by Time
          return parseTime(a.timeOfDay) - parseTime(b.timeOfDay);
      });

      setSteps(sortedSteps);
      autoGeneratedRef.current.clear();
      // Safely set the active day to the first available day in the steps
      if (sortedSteps[0]?.day) {
        setActiveDay(sortedSteps[0].day);
      } else {
        setActiveDay("1");
      }
    } else {
      setSteps([]);
    }
  }, [result]);

  useEffect(() => {
    try {
      const saved = localStorage.getItem('amposta_explorer_ratings');
      if (saved) setRatings(JSON.parse(saved));
    } catch (e) { console.error("Error loading ratings", e); }
  }, []);

  const handleRateStep = (title: string, rating: number) => {
    const newRatings = { ...ratings, [title]: rating };
    setRatings(newRatings);
    localStorage.setItem('amposta_explorer_ratings', JSON.stringify(newRatings));
  };

  const uniqueDays = Array.from(new Set((steps || []).map(s => s?.day))).filter(Boolean);
  const visibleSteps = (steps || []).filter(step => step && step.day === activeDay);

  const bookingCandidates = (steps || []).filter((step, index, self) => {
    if (!step) return false;
    const lower = (step.title || "").toLowerCase();
    const isGeneric = lower.includes("check-in") || lower.includes("check-out") || lower.length < 4;
    return !isGeneric && index === self.findIndex((t) => t?.title === step.title);
  });

  const handleMoveStep = (stepId: string, direction: 'up' | 'down') => {
    const currentIndex = visibleSteps.findIndex(s => s.id === stepId);
    if (currentIndex === -1) return;
    const targetIndex = direction === 'up' ? currentIndex - 1 : currentIndex + 1;
    if (targetIndex < 0 || targetIndex >= visibleSteps.length) return;
    const stepToMove = visibleSteps[currentIndex];
    const stepToSwap = visibleSteps[targetIndex];
    const globalIndex1 = steps.findIndex(s => s.id === stepToMove.id);
    const globalIndex2 = steps.findIndex(s => s.id === stepToSwap.id);

    if (globalIndex1 !== -1 && globalIndex2 !== -1) {
      const newSteps = [...steps];
      [newSteps[globalIndex1], newSteps[globalIndex2]] = [newSteps[globalIndex2], newSteps[globalIndex1]];
      setSteps(newSteps);
    }
  };

  const handleUpdateNotes = (stepId: string, notes: string) => {
    const newSteps = steps.map(s => s.id === stepId ? { ...s, userNotes: notes } : s);
    setSteps(newSteps);
  };

  const handleGenerateImage = async (stepId: string) => {
      const step = steps.find(s => s.id === stepId);
      if (!step) return;
      autoGeneratedRef.current.add(stepId);
      const imageUrl = await generateStepImage(step.title, step.description);
      if (imageUrl) {
          setSteps(currentSteps => currentSteps.map(s => s.id === stepId ? { ...s, imageUrl } : s));
      }
  };

  const handleGenerateInstructions = async (stepId: string) => {
      const step = steps.find(s => s.id === stepId);
      if (!step || step.detailedInstructions) return;
      const instructions = await generateStepInstructions(step.title, step.description, preferences.language);
      if (instructions.length > 0) {
          setSteps(currentSteps => currentSteps.map(s => s.id === stepId ? { ...s, detailedInstructions: instructions } : s));
      }
  };

  const handleFetchNearby = async (stepId: string) => {
      const step = steps.find(s => s.id === stepId);
      if (!step || step.nearbyAttractions) return;
      const nearby = await getNearbyAttractions(step.title, preferences.language);
      if (nearby) {
          setSteps(currentSteps => currentSteps.map(s => s.id === stepId ? { ...s, nearbyAttractions: nearby } : s));
      }
  };

  const isLikelyAttraction = (step: ItineraryStep) => {
     if (!step || !step.title) return false;
     const lowerTitle = step.title.toLowerCase();
     if (lowerTitle.includes('check-in') || lowerTitle.includes('check-out')) return false;
     if (lowerTitle.startsWith('travel to') || lowerTitle.startsWith('viaje a')) return false;
     return true;
  };

  useEffect(() => {
    const generateImagesSequentially = async () => {
        for (const step of steps) {
            if (step && !step.imageUrl && !autoGeneratedRef.current.has(step.id)) {
                autoGeneratedRef.current.add(step.id);
                await handleGenerateImage(step.id);
                await new Promise(resolve => setTimeout(resolve, 3000));
            }
        }
    };
    if (steps.length > 0) generateImagesSequentially();
  }, [steps]);

  const isSpecialEvent = (step: ItineraryStep) => {
     if (!step) return false;
     const text = (step.title + step.description).toLowerCase();
     const eventKeywords = ["festa", "festes", "fira", "festival", "jornada", "diada", "concurs", "marató", "cursa", "mercado", "feria", "fiesta", "cavalcada", "procesión", "desfile", "concert", "concierto", "espectacle"];
     return eventKeywords.some(k => text.includes(k));
  };

  const handleSaveClick = () => {
      if (onSave && onSave()) {
          setShowToast({ msg: t.results.saved_success, type: 'success' });
          setTimeout(() => setShowToast(null), 3000);
      }
  };

  const handleShare = async () => {
      const json = JSON.stringify(preferences);
      const encoded = btoa(encodeURIComponent(json));
      const url = `${window.location.origin}${window.location.pathname}?share=${encoded}`;
      
      try {
        if (navigator.share) {
          await navigator.share({ title: t.results.itinerary_title, text: `Amposta Explorer`, url: url });
        } else {
          await navigator.clipboard.writeText(url);
          setShowToast({ msg: t.results.copied, type: 'info' });
          setTimeout(() => setShowToast(null), 2000);
        }
      } catch (err) { console.error(err); }
  };
  
  const isBookingSource = (url: string) => /thefork|tripadvisor|opentable|reserv|book/.test(url.toLowerCase());
  const getDirectBookingSource = (step: ItineraryStep) => webSources.find(s => (s.title.toLowerCase().includes(step?.title?.toLowerCase() || "") || (step?.title?.toLowerCase() || "").includes(s.title.toLowerCase())) && isBookingSource(s.url));
  const showTaxiCard = true; 

  return (
    <div className="animate-fade-in space-y-6 relative pb-20">
      
      {showToast && (
        <div className={`fixed top-20 left-1/2 transform -translate-x-1/2 px-4 py-2 rounded-lg shadow-xl text-sm z-50 animate-fade-in-up flex items-center gap-2 print:hidden ${showToast.type === 'success' ? 'bg-teal-600 text-white' : 'bg-stone-800 text-white'}`}>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6L9 17l-5-5"/></svg>
          {showToast.msg}
        </div>
      )}

      {/* Header Actions */}
      <div className="bg-white p-3 sm:p-4 rounded-xl shadow-sm border border-slate-100 flex flex-wrap sm:flex-nowrap justify-between items-center gap-3 sticky top-[4rem] z-20 print:static print:shadow-none print:border-none">
        <div>
            <h2 className="font-bold text-lg sm:text-xl text-stone-800 flex items-center gap-2">
               <span className="text-xl sm:text-2xl">🗺️</span> {t.results.itinerary_title}
            </h2>
            {preferences.startDate && (
                <p className="text-xs text-stone-500 mt-1 ml-8 sm:ml-9">
                    {t.results.scheduled_date}: <span className="font-semibold text-teal-600">{new Date(preferences.startDate).toLocaleDateString(preferences.language)}</span>
                </p>
            )}
        </div>
        
        <div className="flex items-center gap-2 w-full sm:w-auto overflow-x-auto no-scrollbar print:hidden">
          {onSave && (
              <button onClick={handleSaveClick} className="flex-1 sm:flex-none text-xs font-bold text-white bg-teal-600 hover:bg-teal-700 px-4 py-2.5 rounded-xl transition-all flex items-center justify-center gap-2 whitespace-nowrap shadow-md shadow-teal-200 active:scale-95">
                 {t.save_btn}
              </button>
          )}

          <button onClick={handleShare} className="flex-1 sm:flex-none text-xs font-bold text-stone-600 bg-stone-100 hover:bg-stone-200 px-3 py-2 rounded-lg transition-colors flex items-center justify-center gap-2 whitespace-nowrap">
            <span className="hidden sm:inline">{t.share_btn}</span>
          </button>
          
          <button onClick={() => window.print()} className="flex-1 sm:flex-none text-xs font-bold text-stone-600 bg-stone-100 hover:bg-red-50 hover:text-red-600 px-3 py-2 rounded-lg transition-colors flex items-center justify-center gap-2 whitespace-nowrap">
             <span className="hidden sm:inline">{t.pdf_btn}</span>
          </button>

          <button onClick={onReset} className="flex-1 sm:flex-none text-xs font-bold text-teal-600 bg-teal-50 px-3 py-2 rounded-lg transition-colors whitespace-nowrap">
            {t.create_new_btn}
          </button>
        </div>
      </div>

      {/* Main Content */}
      <div className="space-y-6">
        {/* If steps exist, render interactive view. If not (parsing failed), render Markdown fallback. */}
        {steps && steps.length > 0 ? (
            <div className="space-y-6">
                
                {/* Day Selector */}
                {uniqueDays.length > 1 && (
                    <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 sticky top-[8.5rem] z-10 bg-stone-50/95 backdrop-blur py-2 print:hidden">
                        <div className="flex items-center gap-2 overflow-x-auto pb-1 no-scrollbar w-full">
                            {uniqueDays.map((day) => (
                            <button
                                key={day}
                                onClick={() => setActiveDay(day)}
                                className={`px-4 py-2 rounded-full text-sm font-bold whitespace-nowrap transition-all border ${
                                activeDay === day 
                                    ? 'bg-teal-600 text-white border-teal-600 shadow-md transform scale-105' 
                                    : 'bg-white text-slate-500 border-slate-200 hover:border-teal-300'
                                }`}
                            >
                                {t.results.day} {day}
                            </button>
                            ))}
                        </div>
                    </div>
                )}

                {/* Day Map REMOVED */}

                {/* Visible Steps */}
                <div className="space-y-0 relative animate-fade-in print:hidden pl-4 md:pl-0">
                        <div className="absolute left-6 top-4 bottom-4 w-0.5 bg-slate-200 hidden md:block z-0"></div>
                        {visibleSteps.map((step, index) => step ? (
                                <div key={step.id} className="relative mb-6">
                                    <div className="absolute left-6 top-8 w-4 h-4 bg-white border-2 border-teal-500 rounded-full transform -translate-x-1/2 z-10 hidden md:block shadow-sm"></div>
                                    <div className="md:pl-12">
                                        <ItineraryStepCard 
                                            step={step} 
                                            index={index} 
                                            totalSteps={visibleSteps.length}
                                            transport={preferences.transport}
                                            theme={preferences.theme}
                                            language={preferences.language}
                                            onMoveUp={() => handleMoveStep(step.id, 'up')}
                                            onMoveDown={() => handleMoveStep(step.id, 'down')}
                                            onUpdateNotes={(notes) => handleUpdateNotes(step.id, notes)}
                                            onGenerateImage={handleGenerateImage}
                                            onGenerateInstructions={handleGenerateInstructions}
                                            onViewBooking={() => setSelectedBookingStep(step)}
                                            onFetchNearby={isLikelyAttraction(step) ? () => handleFetchNearby(step.id) : undefined}
                                            isSpecialEvent={isSpecialEvent(step)}
                                            hasDirectBooking={!!getDirectBookingSource(step)}
                                            userRating={ratings[step.title] || 0}
                                            onRate={(r) => handleRateStep(step.title, r)}
                                        />
                                    </div>
                                </div>
                        ) : null)}
                </div>
                
                {/* Print View */}
                <div className="hidden print:block space-y-4">
                     {steps.map((step, index) => step ? (
                          <ItineraryStepCard key={`print-${step.id}`} step={step} index={index} totalSteps={steps.length} transport={preferences.transport} theme={preferences.theme} language={preferences.language} onMoveUp={()=>{}} onMoveDown={()=>{}} onUpdateNotes={()=>{}} onViewBooking={()=>{}} />
                     ) : null)}
                </div>
            </div>
         ) : (
            <div className="markdown-body prose prose-stone max-w-none bg-white p-6 rounded-xl border border-slate-200">
                <ReactMarkdown>{result.markdown || ""}</ReactMarkdown>
            </div>
         )}
      </div>

      {/* Info Sections */}
      <div className="space-y-4 print:hidden">
           
           {/* Restaurant Recommendations Section */}
           <div className="bg-white rounded-xl border border-slate-200 overflow-hidden shadow-sm">
               <button onClick={() => setIsRestaurantInfoOpen(!isRestaurantInfoOpen)} className="w-full flex justify-between items-center p-4 bg-orange-50 hover:bg-orange-100 transition-colors">
                    <span className="font-bold text-orange-900 flex gap-2"><span>🍽️</span> {t.results.restaurants_title}</span>
               </button>
               {isRestaurantInfoOpen && (
                    <div className="p-0 sm:p-4 bg-orange-50/30">
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                            {RECOMMENDED_RESTAURANTS.map((resto, idx) => (
                                <div key={idx} className="bg-white p-4 rounded-lg border border-orange-100 shadow-sm flex flex-col justify-between">
                                    <div>
                                        <div className="flex justify-between items-start mb-1">
                                            <h4 className="font-bold text-stone-800 text-sm">{resto.name}</h4>
                                            <span className="text-xs font-semibold bg-orange-100 text-orange-800 px-1.5 py-0.5 rounded">{resto.price}</span>
                                        </div>
                                        <div className="text-xs text-stone-500 mb-2 flex items-center gap-1">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
                                            {resto.location}
                                        </div>
                                        <p className="text-xs text-stone-600 italic mb-3">"{resto.specialty[preferences.language]}"</p>
                                    </div>
                                    <a href={`tel:${resto.phone.replace(/\s+/g, '')}`} className="text-xs font-bold text-teal-600 hover:text-teal-800 flex items-center gap-1 mt-auto bg-teal-50 w-fit px-2 py-1 rounded">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path></svg>
                                        {resto.phone}
                                    </a>
                                </div>
                            ))}
                        </div>
                    </div>
               )}
           </div>

           {bookingCandidates.length > 0 && (
                <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
                    <button onClick={() => setIsBookingsOpen(!isBookingsOpen)} className="w-full flex justify-between items-center p-4 bg-slate-50 hover:bg-slate-100">
                        <span className="font-bold text-stone-800 flex gap-2"><span>🎟️</span> {t.results.bookings_title}</span>
                    </button>
                    {isBookingsOpen && (
                        <div className="p-4 divide-y divide-slate-100">
                             {bookingCandidates.map((item, idx) => item && (
                                 <div key={idx} className="py-2 flex justify-between items-center">
                                     <span className="text-sm font-medium">{item.title}</span>
                                     <button onClick={() => setSelectedBookingStep(item)} className="text-xs bg-teal-50 text-teal-700 px-2 py-1 rounded border border-teal-100">{t.results.view_booking_btn}</button>
                                 </div>
                             ))}
                        </div>
                    )}
                </div>
           )}

           <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
                <button onClick={() => setIsDeltaInfoOpen(!isDeltaInfoOpen)} className="w-full flex justify-between items-center p-4 bg-teal-50 hover:bg-teal-100">
                     <span className="font-bold text-teal-900 flex gap-2"><span>🦩</span> {t.delta_info.title}</span>
                </button>
                {isDeltaInfoOpen && <div className="p-5 prose prose-sm max-w-none"><ReactMarkdown>{t.delta_info.content}</ReactMarkdown></div>}
           </div>

           {showTaxiCard && (
               <div className="bg-white rounded-xl border border-slate-200 overflow-hidden shadow-sm">
                   <button onClick={() => setIsTaxiInfoOpen(!isTaxiInfoOpen)} className="w-full flex justify-between items-center p-4 bg-yellow-50 hover:bg-yellow-100 transition-colors">
                        <span className="font-bold text-yellow-900 flex gap-2"><span>🚖</span> {t.taxi_info.title}</span>
                   </button>
                   {isTaxiInfoOpen && (
                        <div className="p-5 prose prose-sm max-w-none bg-yellow-50/30">
                            <ReactMarkdown>{t.taxi_info.content}</ReactMarkdown>
                        </div>
                   )}
               </div>
           )}
      </div>
      
      <div className="bg-slate-50 rounded-xl p-6 border border-slate-200 print:hidden text-center text-xs text-slate-400">
           {t.results.verify_warning}
      </div>

      {selectedBookingStep && (
         <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-0 sm:p-4 bg-black/50 backdrop-blur-sm animate-fade-in print:hidden">
            <div className="bg-white w-full sm:max-w-lg sm:rounded-xl rounded-t-xl max-h-[90vh] flex flex-col animate-fade-in-up">
               <div className="p-4 border-b border-slate-100 flex justify-between items-center bg-slate-50 rounded-t-xl">
                  <h3 className="font-bold text-stone-800 truncate pr-4">{selectedBookingStep.title}</h3>
                  <button onClick={() => setSelectedBookingStep(null)} className="p-2 bg-slate-200 rounded-full hover:bg-slate-300">✕</button>
               </div>
               <div className="p-6 overflow-y-auto space-y-4">
                   <div className="text-sm text-stone-600 prose prose-sm max-w-none"><ReactMarkdown>{selectedBookingStep.description}</ReactMarkdown></div>
                   <a href={`https://www.google.com/search?q=${encodeURIComponent(selectedBookingStep.title + " reservar")}`} target="_blank" rel="noreferrer" className="block w-full text-center py-3 bg-teal-600 text-white font-bold rounded-xl hover:bg-teal-700">{t.results.view_booking_btn} Google</a>
               </div>
            </div>
         </div>
      )}
    </div>
  );
};

export default ResultDisplay;
