
import React, { useState, useEffect, useRef } from 'react';
import ReactMarkdown from 'react-markdown';
import { ItineraryResult, UserPreferences, Transport, ItineraryStep, Theme, GroundingSource } from '../types';
import { TRANSLATIONS } from '../constants';
import ItineraryStepCard from './ItineraryStepCard';
import { generateStepImage, generateStepInstructions, getNearbyAttractions } from '../services/geminiService';

interface ResultDisplayProps {
  result: ItineraryResult;
  preferences: UserPreferences;
  onReset: () => void;
}

const ResultDisplay: React.FC<ResultDisplayProps> = ({ result, preferences, onReset }) => {
  
  const [steps, setSteps] = useState<ItineraryStep[]>([]);
  const [activeDay, setActiveDay] = useState<string>("");
  const [showCopiedToast, setShowCopiedToast] = useState(false);
  const [isBookingsOpen, setIsBookingsOpen] = useState(false);
  const [isDeltaInfoOpen, setIsDeltaInfoOpen] = useState(false);
  const [isTravelTipsOpen, setIsTravelTipsOpen] = useState(false);
  const [selectedBookingStep, setSelectedBookingStep] = useState<ItineraryStep | null>(null);
  const [ratings, setRatings] = useState<Record<string, number>>({});
  
  // Track which steps have been auto-generated to prevent loops
  const autoGeneratedRef = useRef<Set<string>>(new Set());
  
  const mapSources = result.sources.filter(s => s.type === 'map');
  const webSources = result.sources.filter(s => s.type === 'web');

  const t = TRANSLATIONS[preferences.language];

  // Initialize steps from result
  useEffect(() => {
    if (result.steps && result.steps.length > 0) {
      setSteps(result.steps);
      autoGeneratedRef.current.clear(); // Reset tracker on new result
      // Set the first available day as active by default
      if (result.steps[0].day) {
        setActiveDay(result.steps[0].day);
      }
    } else {
      setSteps([]);
    }
  }, [result]);

  // Load ratings from localStorage
  useEffect(() => {
    try {
      const saved = localStorage.getItem('amposta_explorer_ratings');
      if (saved) {
        setRatings(JSON.parse(saved));
      }
    } catch (e) {
      console.error("Error loading ratings", e);
    }
  }, []);

  const handleRateStep = (title: string, rating: number) => {
    const newRatings = { ...ratings, [title]: rating };
    setRatings(newRatings);
    localStorage.setItem('amposta_explorer_ratings', JSON.stringify(newRatings));
  };

  // Derive unique days
  const uniqueDays = Array.from(new Set(steps.map(s => s.day)));

  // Filter steps for the current view
  const visibleSteps = steps.filter(step => step.day === activeDay);

  // Derive potential booking candidates from all steps
  const bookingCandidates = steps.filter((step, index, self) => {
    const lower = step.title.toLowerCase();
    const isGeneric = 
        lower.includes("check-in") || 
        lower.includes("check-out") ||
        lower.length < 4;

    return !isGeneric && 
           index === self.findIndex((t) => t.title === step.title);
  });

  const handleMoveStep = (stepId: string, direction: 'up' | 'down') => {
    // Find the index within the currently visible list
    const currentIndex = visibleSteps.findIndex(s => s.id === stepId);
    if (currentIndex === -1) return;

    const targetIndex = direction === 'up' ? currentIndex - 1 : currentIndex + 1;

    // Check bounds within visible list
    if (targetIndex < 0 || targetIndex >= visibleSteps.length) return;

    const stepToMove = visibleSteps[currentIndex];
    const stepToSwap = visibleSteps[targetIndex];

    // Find their real indices in the global source array
    const globalIndex1 = steps.findIndex(s => s.id === stepToMove.id);
    const globalIndex2 = steps.findIndex(s => s.id === stepToSwap.id);

    if (globalIndex1 !== -1 && globalIndex2 !== -1) {
      const newSteps = [...steps];
      [newSteps[globalIndex1], newSteps[globalIndex2]] = [newSteps[globalIndex2], newSteps[globalIndex1]];
      setSteps(newSteps);
    }
  };

  const handleUpdateNotes = (stepId: string, notes: string) => {
    const newSteps = steps.map(s => 
      s.id === stepId ? { ...s, userNotes: notes } : s
    );
    setSteps(newSteps);
  };

  const handleGenerateImage = async (stepId: string) => {
      const step = steps.find(s => s.id === stepId);
      if (!step) return;
      
      // Mark as requested to avoid duplicate triggers
      autoGeneratedRef.current.add(stepId);

      const imageUrl = await generateStepImage(step.title, step.description);
      if (imageUrl) {
          // Use functional update to ensure concurrent requests don't overwrite each other
          setSteps(currentSteps => currentSteps.map(s => s.id === stepId ? { ...s, imageUrl } : s));
      }
  };

  const handleGenerateInstructions = async (stepId: string) => {
      const step = steps.find(s => s.id === stepId);
      if (!step || step.detailedInstructions) return;

      const instructions = await generateStepInstructions(step.title, step.description, preferences.language);
      if (instructions.length > 0) {
          setSteps(currentSteps => currentSteps.map(s => s.id === stepId ? { ...s, detailedInstructions: instructions } : s));
      }
  };

  const handleFetchNearby = async (stepId: string) => {
      const step = steps.find(s => s.id === stepId);
      if (!step || step.nearbyAttractions) return;

      const nearby = await getNearbyAttractions(step.title, preferences.language);
      if (nearby) {
          setSteps(currentSteps => currentSteps.map(s => s.id === stepId ? { ...s, nearbyAttractions: nearby } : s));
      }
  };

  // Auto-trigger image generation for missing images SEQUENTIALLY to avoid 429 Rate Limits
  useEffect(() => {
    const generateImagesSequentially = async () => {
        for (const step of steps) {
            if (!step.imageUrl && !autoGeneratedRef.current.has(step.id)) {
                // Add to ref immediately to prevent re-entry
                autoGeneratedRef.current.add(step.id);
                
                // Trigger generation
                await handleGenerateImage(step.id);
                
                // Wait 3 seconds before the next request to respect API rate limits
                await new Promise(resolve => setTimeout(resolve, 3000));
            }
        }
    };

    generateImagesSequentially();
  }, [steps]);

  // Helper to detect if a step matches keywords for special events/festivals
  const isSpecialEvent = (step: ItineraryStep) => {
     const title = step.title.toLowerCase();
     const desc = step.description.toLowerCase();
     const eventKeywords = [
        "festa", "festes", "fira", "festival", 
        "jornada gas", "jornadas gas", // Jornades gastronòmiques
        "diada", "concurs", "marató", "cursa",
        "mercado", "feria", "fiesta", // Spanish
        "nit de", "noche de",
        "cavalcada", "cabalgata", "processó", "procesión", "desfilada", "desfile", // Parades
        "concert", "concierto", "espectacle", "espectáculo",
        "aplec", "trobada", "vetllada"
     ];
     // Check title primarily, or strong signal in description
     return eventKeywords.some(k => title.includes(k));
  };

  const getShareUrl = () => {
      const json = JSON.stringify(preferences);
      const encoded = btoa(encodeURIComponent(json));
      return `${window.location.origin}${window.location.pathname}?share=${encoded}`;
  };

  const handleShare = async () => {
    try {
      const url = getShareUrl();
      if (navigator.share) {
        await navigator.share({
          title: t.results.itinerary_title,
          text: `${t.results.itinerary_title} - Amposta`,
          url: url
        });
      } else {
        await navigator.clipboard.writeText(url);
        setShowCopiedToast(true);
        setTimeout(() => setShowCopiedToast(false), 2000);
      }
    } catch (err) {
      console.error('Error sharing:', err);
    }
  };

  const handleEmail = () => {
      const url = getShareUrl();
      const subject = encodeURIComponent(`${t.results.itinerary_title}: Amposta Explorer`);
      const body = encodeURIComponent(`${t.title} - ${t.subtitle}\n\n${t.results.suggested_route}: ${url}`);
      window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };

  const handlePdf = () => {
      window.print();
  };

  const renderRiverNavigation = () => {
    if (preferences.transport !== Transport.RIVER || !preferences.includeUpriver) return null;

    const riverStops = [
        { name: "Amposta", query: "Embarcadero de Amposta" },
        { name: "Tortosa", query: "Embarcadero de Tortosa" },
        { name: "Miravet", query: "Pas de Barca Miravet" }
    ];

    const fullRouteUrl = `https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent("Embarcadero de Amposta")}&destination=${encodeURIComponent("Pas de Barca Miravet")}&waypoints=${encodeURIComponent("Embarcadero de Tortosa")}&travelmode=driving`;

    return (
        <div className="bg-blue-50 border border-blue-200 rounded-xl p-5 mb-6 animate-fade-in print:hidden">
             <div className="flex items-start justify-between gap-4 mb-3">
                <div>
                    <h3 className="font-bold text-blue-900 flex items-center gap-2 text-lg">
                        <span className="text-2xl">🛳️</span> {t.results.river_route_title}
                    </h3>
                    <p className="text-sm text-blue-800 mt-1 leading-relaxed">
                        {t.results.river_note_upriver}
                    </p>
                </div>
             </div>

             <div className="space-y-3 mt-4">
                 <a 
                    href={fullRouteUrl}
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="w-full flex items-center justify-center gap-2 bg-white border-2 border-blue-200 hover:border-blue-400 text-blue-700 font-bold py-3 px-4 rounded-xl shadow-sm transition-all hover:shadow-md hover:scale-[1.01]"
                 >
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 11l19-9-9 19-2-8-8-2z"></path></svg>
                    {t.results.view_full_river_route}
                 </a>

                 <div>
                    <h4 className="text-xs font-bold text-blue-800 uppercase mb-2 tracking-wider ml-1">{t.results.pier_locations}</h4>
                    <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                        {riverStops.map((stop, idx) => (
                            <a 
                                key={idx}
                                href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(stop.query)}`}
                                target="_blank" 
                                rel="noopener noreferrer"
                                className="flex items-center gap-2 bg-white/80 p-2.5 rounded-lg border border-blue-100 hover:bg-white hover:border-blue-300 transition-all group"
                            >
                                <div className="bg-blue-100 text-blue-600 font-bold w-6 h-6 flex items-center justify-center rounded-full text-xs shrink-0 group-hover:bg-blue-600 group-hover:text-white transition-colors">
                                    {idx + 1}
                                </div>
                                <span className="text-sm font-medium text-slate-700 group-hover:text-blue-900">{stop.name}</span>
                            </a>
                        ))}
                    </div>
                 </div>
             </div>
        </div>
    );
  };

  const renderRouteButton = () => {
    let mapMode = 'driving';
    if (preferences.transport === Transport.WALKING) {
      mapMode = 'walking';
    } else if (preferences.transport === Transport.BUS || preferences.transport === Transport.TRAIN) {
      mapMode = 'transit';
    } else if (preferences.transport === Transport.BIKE) {
      mapMode = 'bicycling';
    } else if (preferences.transport === Transport.MIX) {
      const hasCar = preferences.customTransports?.includes(Transport.CAR);
      mapMode = hasCar ? 'driving' : 'transit';
    }

    // Get locations from visible steps
    let locations: string[] = [];

    if (visibleSteps.length > 0) {
        locations = visibleSteps.map(step => {
            // Try to find a precise address from grounding chunks first
            const matchedSource = mapSources.find(s => 
                s.title.toLowerCase().includes(step.title.toLowerCase()) || 
                step.title.toLowerCase().includes(s.title.toLowerCase())
            );
            // Clean up title for better search results
            let cleanTitle = step.title.replace(/[:()].*$/, '').trim();
            return matchedSource ? matchedSource.title : `${cleanTitle}, Amposta`;
        });
    }

    // Remove duplicates
    locations = locations.filter((loc, i, arr) => i === 0 || loc !== arr[i-1]);

    if (locations.length === 0) return null;

    let origin = "Amposta, Tarragona"; 

    // --- ENHANCED RIVER LOGIC ---
    // If river transport, we want the route to start at the river port
    if (preferences.transport === Transport.RIVER) {
         if (preferences.includeUpriver) {
             origin = "Embarcadero de Amposta";
         } else {
             origin = "Club Nàutic Amposta"; 
         }
    } else if (locations.length > 0) {
        // If not river, start at the first activity
        origin = locations[0];
        locations = locations.slice(1); // Remove first item from waypoints since it's now origin
    }

    if (locations.length === 0 && origin === "Amposta, Tarragona") return null;

    // Construct Universal Google Maps URL (No API Key required)
    const baseUrl = "https://www.google.com/maps/dir/?api=1";
    const originParam = `&origin=${encodeURIComponent(origin)}`;
    
    let destinationParam = "";
    let waypointsParam = "";

    if (locations.length > 0) {
        // Last location is destination
        destinationParam = `&destination=${encodeURIComponent(locations[locations.length - 1])}`;
        
        // Others are waypoints
        if (locations.length > 1) {
            const waypoints = locations.slice(0, -1);
            waypointsParam = `&waypoints=${waypoints.map(w => encodeURIComponent(w)).join('|')}`;
        }
    } else {
        // Only origin known, just search it
        return (
            <a 
                href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(origin)}`}
                target="_blank"
                rel="noopener noreferrer"
                className="w-full h-32 bg-slate-100 rounded-2xl border border-slate-200 flex items-center justify-center gap-3 text-stone-600 font-semibold hover:bg-slate-200 hover:text-teal-700 transition-all group print:hidden"
            >
                <span className="text-3xl group-hover:scale-110 transition-transform">🗺️</span>
                <span>{t.results.view_map}</span>
            </a>
        );
    }

    const fullUrl = `${baseUrl}${originParam}${destinationParam}${waypointsParam}&travelmode=${mapMode}`;

    return (
      <div className="flex flex-col gap-3 mb-8 print:hidden">
        <a
            href={fullUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="w-full py-6 px-6 bg-gradient-to-r from-slate-100 to-white rounded-2xl border-2 border-slate-200 border-dashed flex items-center justify-center gap-4 text-stone-600 hover:border-teal-400 hover:text-teal-700 hover:bg-teal-50/30 transition-all group shadow-sm hover:shadow-md cursor-pointer"
        >
            <div className="bg-white p-3 rounded-full shadow-sm group-hover:scale-110 transition-transform">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-teal-600"><polygon points="3 11 22 2 13 21 11 13 3 11"></polygon></svg>
            </div>
            <div className="text-left">
                <span className="block font-bold text-lg">{t.results.suggested_route} ({t.results.day} {activeDay})</span>
                <span className="block text-sm text-slate-500 group-hover:text-teal-600">
                    {t.results.view_map} Google Maps &rarr;
                </span>
            </div>
        </a>

        {preferences.transport === Transport.RIVER && preferences.includeUpriver ? (
             renderRiverNavigation()
        ) : (
             preferences.transport === Transport.RIVER && (
                 <div className="bg-blue-50 border border-blue-100 rounded-lg p-3 flex items-start gap-3 animate-fade-in">
                     <span className="text-xl">🛥️</span>
                     <p className="text-xs text-blue-800 leading-relaxed">
                       <strong>Nota:</strong> {t.results.river_note_local}
                     </p>
                 </div>
             )
        )}
      </div>
    );
  };
  
  // Helper to determine if a URL is a known booking platform
  const isBookingSource = (url: string) => {
    const lower = url.toLowerCase();
    return lower.includes('thefork') || 
           lower.includes('tripadvisor') || 
           lower.includes('opentable') || 
           lower.includes('covermanager') || 
           lower.includes('reserv') ||
           lower.includes('book');
  };

  const getDirectBookingSource = (step: ItineraryStep) => {
    return webSources.find(s => 
        (s.title.toLowerCase().includes(step.title.toLowerCase()) || 
         step.title.toLowerCase().includes(s.title.toLowerCase())) &&
        isBookingSource(s.url)
    );
  };
  
  // Heuristic parser to extract details from description text
  const extractDetails = (text: string) => {
    let price: string | null = null;
    let hours: string | null = null;

    // Look for lines or phrases
    const lines = text.split(/\n|\. /);
    
    for (const line of lines) {
        // Price heuristics - enhanced for better detection of actual prices
        if (!price && /(preu|precio|price|cost|entrada|ticket).{0,20}(\d|€|\$|\d+.{0,5}(eur|euros))/i.test(line) && line.length < 100) {
            price = line.replace(/(\*\*|__)/g, '').trim();
            // Remove ending dot if present
            if (price.endsWith('.')) price = price.slice(0, -1);
        }
        // Hours heuristics - enhanced for time formats
        if (!hours && /(horari|horario|hours|obertura|apertura|open|dilluns|dimarts|lunes|martes|monday).{0,20}\d/i.test(line) && line.length < 120) {
            hours = line.replace(/(\*\*|__)/g, '').trim();
            if (hours.endsWith('.')) hours = hours.slice(0, -1);
        }
    }
    return { price, hours };
  };

  return (
    <div className="animate-fade-in space-y-8 relative">
      
      {showCopiedToast && (
        <div className="fixed top-20 left-1/2 transform -translate-x-1/2 bg-stone-800 text-white px-4 py-2 rounded-lg shadow-xl text-sm z-50 animate-fade-in-up flex items-center gap-2 print:hidden">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6L9 17l-5-5"/></svg>
          Link copied
        </div>
      )}

      {/* Header Actions */}
      <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4 bg-white p-4 rounded-xl shadow-sm border border-slate-100 sticky top-0 z-20 print:static print:shadow-none print:border-none print:p-0">
        <div>
            <h2 className="font-bold text-xl text-stone-800 flex items-center gap-2">
            <span className="text-2xl">🗺️</span> {t.results.itinerary_title}
            </h2>
            {preferences.startDate && (
                <p className="text-xs text-stone-500 mt-1 ml-9">
                    {t.results.scheduled_date}: <span className="font-semibold text-teal-600">{new Date(preferences.startDate).toLocaleDateString(preferences.language, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</span>
                </p>
            )}
        </div>
        <div className="flex items-center gap-2 self-start sm:self-auto print:hidden">
          <button 
            onClick={handleShare}
            className="text-sm font-medium text-slate-600 hover:text-teal-700 bg-slate-50 hover:bg-teal-50 px-3 py-2 rounded-lg transition-colors flex items-center gap-2"
            title={t.share_btn}
          >
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="18" cy="5" r="3"></circle><circle cx="6" cy="12" r="3"></circle><circle cx="18" cy="19" r="3"></circle><line x1="8.59" y1="13.51" x2="15.42" y2="17.49"></line><line x1="15.41" y1="6.51" x2="8.59" y2="10.49"></line></svg>
            <span className="hidden sm:inline">{t.share_btn}</span>
          </button>
          
          <button
            onClick={handlePdf}
            className="text-sm font-medium text-slate-600 hover:text-red-700 bg-slate-50 hover:bg-red-50 px-3 py-2 rounded-lg transition-colors flex items-center gap-2"
            title={t.pdf_btn}
          >
             <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
             <span className="hidden sm:inline">{t.pdf_btn}</span>
          </button>

          <button
            onClick={handleEmail}
            className="text-sm font-medium text-slate-600 hover:text-blue-700 bg-slate-50 hover:bg-blue-50 px-3 py-2 rounded-lg transition-colors flex items-center gap-2"
            title={t.email_btn}
          >
             <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>
             <span className="hidden sm:inline">{t.email_btn}</span>
          </button>

          <button 
            onClick={onReset}
            className="text-sm font-medium text-teal-600 hover:text-teal-700 bg-teal-50 px-3 py-2 rounded-lg transition-colors whitespace-nowrap"
          >
            {t.create_new_btn}
          </button>
        </div>
      </div>

      {/* Decorative Header */}
      <div className="rounded-2xl shadow-sm border border-slate-100 overflow-hidden bg-white print:border-none print:shadow-none">
        <div className="h-32 bg-gradient-to-r from-teal-600 to-blue-600 relative overflow-hidden print:hidden">
             <div className="absolute inset-0 bg-black/10"></div>
             <div className="absolute bottom-4 left-6 text-white font-bold text-2xl">Amposta & Delta</div>
        </div>
        
        {steps.length > 0 && (
            <div className="border-b border-slate-100 p-6 pb-0 print:hidden">
                {renderRouteButton()}
            </div>
        )}
        
        <div className="p-6 md:p-8 print:p-0">
             {steps.length > 0 ? (
                <div className="space-y-6">
                  
                  <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 print:hidden">
                     <h3 className="text-lg font-bold text-stone-800">{t.results.plan_title}</h3>
                     
                     {uniqueDays.length > 1 && (
                       <div className="flex items-center gap-2 overflow-x-auto pb-2 md:pb-0 no-scrollbar">
                         {uniqueDays.map((day) => (
                           <button
                             key={day}
                             onClick={() => setActiveDay(day)}
                             className={`px-4 py-2 rounded-lg text-sm font-medium whitespace-nowrap transition-all ${
                               activeDay === day 
                                 ? 'bg-teal-600 text-white shadow-md shadow-teal-200' 
                                 : 'bg-slate-100 text-slate-600 hover:bg-teal-50 hover:text-teal-700'
                             }`}
                           >
                             {t.results.day} {day}
                           </button>
                         ))}
                       </div>
                     )}
                  </div>

                  {/* PRINT VIEW: Show all steps when printing, otherwise show visibleSteps */}
                  <div className="space-y-4 animate-fade-in hidden print:block">
                     {steps.map((step, index) => {
                        const directBooking = getDirectBookingSource(step);
                        return (
                          <ItineraryStepCard 
                              key={`print-${step.id}`} 
                              step={step} 
                              index={index} 
                              totalSteps={steps.length}
                              transport={preferences.transport}
                              theme={preferences.theme}
                              language={preferences.language}
                              onMoveUp={() => {}} 
                              onMoveDown={() => {}}
                              onUpdateNotes={() => {}}
                              onGenerateImage={handleGenerateImage}
                              onGenerateInstructions={handleGenerateInstructions}
                              onViewBooking={() => setSelectedBookingStep(step)}
                              onFetchNearby={() => handleFetchNearby(step.id)}
                              isSpecialEvent={isSpecialEvent(step)}
                              hasDirectBooking={!!directBooking}
                              userRating={ratings[step.title] || 0}
                              onRate={(r) => handleRateStep(step.title, r)}
                          />
                        );
                     })}
                     <div className="mt-4 pt-2 border-t border-slate-100 text-xs text-slate-500 italic">
                        {t.results.verify_warning}
                     </div>
                  </div>

                  <div className="space-y-4 animate-fade-in print:hidden">
                        {visibleSteps.map((step, index) => {
                            const directBooking = getDirectBookingSource(step);
                            return (
                                <ItineraryStepCard 
                                    key={step.id} 
                                    step={step} 
                                    index={index} 
                                    totalSteps={visibleSteps.length}
                                    transport={preferences.transport}
                                    theme={preferences.theme}
                                    language={preferences.language}
                                    onMoveUp={() => handleMoveStep(step.id, 'up')}
                                    onMoveDown={() => handleMoveStep(step.id, 'down')}
                                    onUpdateNotes={(notes) => handleUpdateNotes(step.id, notes)}
                                    onGenerateImage={handleGenerateImage}
                                    onGenerateInstructions={handleGenerateInstructions}
                                    onViewBooking={() => setSelectedBookingStep(step)}
                                    onFetchNearby={() => handleFetchNearby(step.id)}
                                    isSpecialEvent={isSpecialEvent(step)}
                                    hasDirectBooking={!!directBooking}
                                    userRating={ratings[step.title] || 0}
                                    onRate={(r) => handleRateStep(step.title, r)}
                                />
                            );
                        })}

                        <div className="mt-6 flex justify-center">
                            <p className="text-xs text-slate-400 italic bg-slate-50 px-4 py-2 rounded-lg border border-slate-100">
                                {t.results.verify_warning}
                            </p>
                        </div>
                    </div>

                    {steps.length === 0 && (
                        <div className="text-center py-10 text-slate-500">
                        {t.results.no_activities}
                        </div>
                    )}

                </div>
             ) : (
                <div className="markdown-body prose prose-stone max-w-none">
                    <ReactMarkdown>{result.markdown}</ReactMarkdown>
                </div>
             )}
        </div>
      </div>
      
      {/* Bookings Section */}
      {bookingCandidates.length > 0 && (
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden mb-8 print:hidden">
            <button 
                onClick={() => setIsBookingsOpen(!isBookingsOpen)}
                className="w-full flex items-center justify-between p-4 bg-slate-50 hover:bg-slate-100 transition-colors"
            >
                <div className="flex items-center gap-2">
                    <span className="text-xl">🎟️</span>
                    <div className="text-left">
                        <h3 className="font-bold text-stone-800">{t.results.bookings_title}</h3>
                        <p className="text-xs text-slate-500">{t.results.bookings_subtitle}</p>
                    </div>
                </div>
                <div className={`transform transition-transform duration-200 ${isBookingsOpen ? 'rotate-180' : ''}`}>
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="6 9 12 15 18 9"></polyline></svg>
                </div>
            </button>
            
            {isBookingsOpen && (
                <div className="p-4 divide-y divide-slate-100 animate-fade-in">
                    {bookingCandidates.map((item, idx) => {
                         const relevantSource = webSources.find(s => 
                             s.title.toLowerCase().includes(item.title.toLowerCase()) || 
                             item.title.toLowerCase().includes(s.title.toLowerCase())
                         );
                         const isRestaurant = 
                            preferences.theme === Theme.GASTRONOMIC || 
                            /restaurante|arroceria|bistro|gastrobar/i.test(item.title) || 
                            /almuerzo|cena|degustaci|menú/i.test(item.description);
                         
                         const showReservation = isRestaurant && !/museo|centre|centro|exposición/i.test(item.title);
                         const searchUrl = `https://www.google.com/search?q=reservar+entradas+${encodeURIComponent(item.title)}+Amposta`;
                         
                         // Enhanced Booking Logic
                         // Priority: 1. Direct Booking Platform (TheFork, etc), 2. Google Maps Place Link (has Reserve btn), 3. Generic Search
                         let bookingUrl = `https://www.google.com/search?q=reservar+mesa+${encodeURIComponent(item.title)}+Amposta`;
                         
                         const directBookingSource = getDirectBookingSource(item);

                         const mapPlaceSource = mapSources.find(s => 
                            s.title.toLowerCase().includes(item.title.toLowerCase()) || item.title.toLowerCase().includes(s.title.toLowerCase())
                         );

                         if (directBookingSource) {
                             bookingUrl = directBookingSource.url;
                         } else if (mapPlaceSource) {
                             bookingUrl = mapPlaceSource.url;
                         }

                         return (
                            <div key={idx} className="py-3 first:pt-0 last:pb-0 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                                <div>
                                    <span className="font-medium text-stone-700 block">{item.title}</span>
                                    <span className="text-xs text-slate-400">{t.results.day} {item.day} • {item.timeOfDay}</span>
                                </div>
                                <div className="flex items-center gap-2 shrink-0">
                                    <button
                                        onClick={() => setSelectedBookingStep(item)}
                                        className="text-xs font-medium text-teal-700 bg-teal-50 border border-teal-100 hover:bg-teal-100 px-3 py-2 rounded-lg transition-colors flex items-center gap-1"
                                    >
                                        {t.results.view_booking_btn}
                                    </button>

                                    {relevantSource && (
                                         <a 
                                            href={relevantSource.url}
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            className="text-xs font-medium text-slate-600 bg-slate-100 hover:bg-slate-200 px-3 py-2 rounded-lg transition-colors"
                                         >
                                            {t.results.web_info}
                                         </a>
                                    )}
                                    
                                    {showReservation ? (
                                        <a 
                                            href={bookingUrl}
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            className={`text-xs font-medium border px-3 py-2 rounded-lg transition-colors flex items-center gap-1 ${directBookingSource ? 'bg-amber-100 text-amber-900 border-amber-200 hover:bg-amber-200' : 'text-amber-700 bg-amber-50 border-amber-100 hover:bg-amber-100'}`}
                                        >
                                            {t.results.book_table} {directBookingSource && '⭐'}
                                        </a>
                                    ) : (
                                        <a 
                                            href={searchUrl}
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            className="text-xs font-medium text-teal-700 bg-teal-50 border border-teal-100 hover:bg-teal-100 px-3 py-2 rounded-lg transition-colors flex items-center gap-1"
                                        >
                                            {t.results.search_tickets} ↗
                                        </a>
                                    )}
                                </div>
                            </div>
                         );
                    })}
                </div>
            )}
        </div>
      )}

      {/* Discover Delta Section */}
      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden mb-8 print:hidden">
          <button
              onClick={() => setIsDeltaInfoOpen(!isDeltaInfoOpen)}
              className="w-full flex items-center justify-between p-4 bg-teal-50 hover:bg-teal-100 transition-colors"
          >
              <div className="flex items-center gap-2">
                  <span className="text-xl">🦩</span>
                  <div className="text-left">
                      <h3 className="font-bold text-teal-900">{t.delta_info.title}</h3>
                      <p className="text-xs text-teal-700">{t.delta_info.subtitle}</p>
                  </div>
              </div>
              <div className={`transform transition-transform duration-200 ${isDeltaInfoOpen ? 'rotate-180' : ''}`}>
                   <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="6 9 12 15 18 9"></polyline></svg>
              </div>
          </button>
          {isDeltaInfoOpen && (
              <div className="p-6 prose prose-stone prose-sm max-w-none animate-fade-in bg-white">
                  <ReactMarkdown>{t.delta_info.content}</ReactMarkdown>
              </div>
          )}
      </div>

      {/* Travel Tips Section */}
      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden mb-8 print:hidden">
          <button
              onClick={() => setIsTravelTipsOpen(!isTravelTipsOpen)}
              className="w-full flex items-center justify-between p-4 bg-orange-50 hover:bg-orange-100 transition-colors"
          >
              <div className="flex items-center gap-2">
                  <span className="text-xl">💡</span>
                  <div className="text-left">
                      <h3 className="font-bold text-orange-900">{t.travel_tips.title}</h3>
                      <p className="text-xs text-orange-700">{t.travel_tips.subtitle}</p>
                  </div>
              </div>
              <div className={`transform transition-transform duration-200 ${isTravelTipsOpen ? 'rotate-180' : ''}`}>
                   <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="6 9 12 15 18 9"></polyline></svg>
              </div>
          </button>
          {isTravelTipsOpen && (
              <div className="p-6 prose prose-stone prose-sm max-w-none animate-fade-in bg-white">
                  <ReactMarkdown>{t.travel_tips.content}</ReactMarkdown>
              </div>
          )}
      </div>

      {/* Booking Info Modal (Enhanced) */}
      {selectedBookingStep && (
         <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-sm animate-fade-in print:hidden">
            <div className="bg-white rounded-xl shadow-2xl w-full max-w-lg overflow-hidden animate-fade-in-up flex flex-col max-h-[90vh]">
               <div className="p-5 border-b border-slate-100 flex justify-between items-center bg-slate-50 shrink-0">
                  <h3 className="font-bold text-lg text-stone-800 flex items-center gap-2">
                    <span className="text-xl">🎟️</span> {t.results.view_booking_btn}: {selectedBookingStep.title}
                  </h3>
                  <button onClick={() => setSelectedBookingStep(null)} className="text-slate-400 hover:text-slate-600">
                     <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
                  </button>
               </div>
               
               <div className="p-6 overflow-y-auto">
                  {/* Extracted Details Section */}
                  {(() => {
                      const { price, hours } = extractDetails(selectedBookingStep.description);
                      if (price || hours) {
                          return (
                              <div className="mb-6 p-4 bg-blue-50 border border-blue-100 rounded-xl space-y-3">
                                  {hours && (
                                      <div className="flex items-start gap-3">
                                          <div className="bg-blue-100 p-1.5 rounded-lg text-blue-600 mt-0.5">
                                             <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>
                                          </div>
                                          <div>
                                              <span className="block text-xs font-bold text-blue-800 uppercase tracking-wide">Horario / Hours</span>
                                              <span className="text-sm text-blue-900 font-medium">{hours}</span>
                                          </div>
                                      </div>
                                  )}
                                  {price && (
                                      <div className="flex items-start gap-3">
                                          <div className="bg-blue-100 p-1.5 rounded-lg text-blue-600 mt-0.5">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="12" y1="1" x2="12" y2="23"></line><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"></path></svg>
                                          </div>
                                          <div>
                                              <span className="block text-xs font-bold text-blue-800 uppercase tracking-wide">Precio / Price</span>
                                              <span className="text-sm text-blue-900 font-medium">{price}</span>
                                          </div>
                                      </div>
                                  )}
                              </div>
                          );
                      }
                      return null;
                  })()}

                  <div className="text-sm text-stone-600 prose prose-sm max-w-none">
                     <ReactMarkdown>{selectedBookingStep.description}</ReactMarkdown>
                  </div>

                  <div className="mt-8 flex flex-col gap-3">
                     <h4 className="text-xs font-bold text-stone-400 uppercase">Enlaces de reserva e info</h4>
                     <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                        {(() => {
                            // Enhanced Modal Logic
                            const matchedWebSource = webSources.find(s => 
                                s.title.toLowerCase().includes(selectedBookingStep.title.toLowerCase()) || 
                                selectedBookingStep.title.toLowerCase().includes(s.title.toLowerCase())
                            );
                            
                            const matchedMapSource = mapSources.find(s => 
                                s.title.toLowerCase().includes(selectedBookingStep.title.toLowerCase()) || 
                                selectedBookingStep.title.toLowerCase().includes(s.title.toLowerCase())
                            );
                            
                            const directBooking = getDirectBookingSource(selectedBookingStep);

                            return (
                                <>
                                    {directBooking ? (
                                        <a 
                                            href={directBooking.url}
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            className="col-span-1 sm:col-span-2 text-center text-sm font-bold bg-amber-500 hover:bg-amber-600 text-white py-3 rounded-xl transition-colors flex items-center justify-center gap-2 shadow-md hover:scale-[1.01]"
                                        >
                                            <span>📅</span> Reservar / Book Now
                                        </a>
                                    ) : null}

                                    {matchedWebSource ? (
                                        <a 
                                            href={matchedWebSource.url}
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            className={`text-center text-sm font-bold py-3 rounded-xl transition-colors flex items-center justify-center gap-2 shadow-sm ${directBooking ? 'bg-slate-100 text-stone-700 hover:bg-slate-200' : 'col-span-1 sm:col-span-2 bg-teal-600 hover:bg-teal-700 text-white'}`}
                                        >
                                            <span>🌍</span> {t.results.web_info}
                                        </a>
                                    ) : (
                                        !directBooking && (
                                            <a 
                                                href={`https://www.google.com/search?q=${encodeURIComponent(selectedBookingStep.title + " Amposta oficial")}`}
                                                target="_blank"
                                                rel="noopener noreferrer"
                                                className="col-span-1 sm:col-span-2 text-center text-sm font-bold bg-teal-600 hover:bg-teal-700 text-white py-3 rounded-xl transition-colors flex items-center justify-center gap-2 shadow-sm"
                                            >
                                                <span>🔎</span> Buscar Web Oficial
                                            </a>
                                        )
                                    )}

                                    {matchedMapSource ? (
                                        <a 
                                            href={matchedMapSource.url}
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            className="text-center text-sm font-medium bg-slate-100 hover:bg-slate-200 text-stone-700 py-3 rounded-xl transition-colors flex items-center justify-center gap-2"
                                        >
                                            <span>📍</span> Google Maps
                                        </a>
                                    ) : (
                                        <a 
                                            href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(selectedBookingStep.title + " Amposta")}`}
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            className="text-center text-sm font-medium bg-slate-100 hover:bg-slate-200 text-stone-700 py-3 rounded-xl transition-colors flex items-center justify-center gap-2"
                                        >
                                            <span>📍</span> Google Maps
                                        </a>
                                    )}

                                     <a 
                                        href={`https://www.tripadvisor.com/Search?q=${encodeURIComponent(selectedBookingStep.title + " Amposta")}`}
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        className="text-center text-sm font-medium bg-teal-50 hover:bg-teal-100 text-teal-800 py-3 rounded-xl transition-colors flex items-center justify-center gap-2"
                                     >
                                        <span>🦉</span> TripAdvisor
                                     </a>
                                </>
                            );
                        })()}
                     </div>
                  </div>
               </div>
            </div>
         </div>
      )}

      {/* Map Locations Cards */}
      {mapSources.length > 0 && (
        <div className="space-y-4 print:hidden">
           <h3 className="text-lg font-bold text-stone-800 flex items-center gap-2 px-1">
             <span className="text-red-500">📍</span> {t.results.detected_places}
           </h3>
           <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
             {mapSources.map((source, index) => (
                <a 
                  key={index}
                  href={source.url} 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="flex flex-col bg-white rounded-xl border border-slate-200 p-4 hover:shadow-lg hover:border-red-200 transition-all group"
                >
                  <div className="flex items-center justify-between mb-2">
                    <div className="bg-red-50 text-red-500 p-2 rounded-full group-hover:bg-red-500 group-hover:text-white transition-colors">
                      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
                    </div>
                  </div>
                  <span className="font-semibold text-stone-800 group-hover:text-red-600 transition-colors">
                    {source.title}
                  </span>
                  <span className="text-xs text-slate-500 mt-2 flex items-center gap-1">
                    {t.results.view_map} &rarr;
                  </span>
                </a>
             ))}
           </div>
        </div>
      )}

      {/* Web Sources */}
      {webSources.length > 0 && (
        <div className="bg-slate-50 rounded-xl p-6 border border-slate-200 print:hidden">
          <h3 className="text-sm font-semibold text-slate-500 uppercase tracking-wider mb-4 flex items-center gap-2">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="16" x2="12" y2="12"/><line x1="12" y1="8" x2="12.01" y2="8"/></svg>
            {t.results.verified_sources}
          </h3>
          <ul className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {webSources.map((source, index) => (
              <li key={index}>
                <a 
                  href={source.url} 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="flex items-center gap-3 p-3 bg-white rounded-lg border border-slate-200 hover:border-teal-400 hover:shadow-md transition-all group"
                >
                    <div className="bg-slate-100 p-2 rounded-full group-hover:bg-teal-50 transition-colors">
                        <svg className="w-4 h-4 text-slate-500 group-hover:text-teal-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                        </svg>
                    </div>
                    <span className="text-sm text-stone-700 font-medium truncate w-full">
                        {source.title}
                    </span>
                </a>
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
};

export default ResultDisplay;
