

import React, { useState, useEffect, useRef } from 'react';
import ReactMarkdown from 'react-markdown';
import { ItineraryResult, UserPreferences, Transport, ItineraryStep, Theme, GroundingSource } from '../types';
import { TRANSLATIONS } from '../constants';
import ItineraryStepCard from './ItineraryStepCard';
import { generateStepImage, generateStepInstructions, getNearbyAttractions } from '../services/geminiService';

interface ResultDisplayProps {
  result: ItineraryResult;
  preferences: UserPreferences;
  onReset: () => void;
  onSave?: () => boolean; // New prop for saving
}

const ResultDisplay: React.FC<ResultDisplayProps> = ({ result, preferences, onReset, onSave }) => {
  
  const [steps, setSteps] = useState<ItineraryStep[]>([]);
  const [activeDay, setActiveDay] = useState<string>("");
  const [showToast, setShowToast] = useState<{msg: string, type: 'success' | 'info'} | null>(null);
  const [isBookingsOpen, setIsBookingsOpen] = useState(false);
  const [isDeltaInfoOpen, setIsDeltaInfoOpen] = useState(false);
  const [isTravelTipsOpen, setIsTravelTipsOpen] = useState(false);
  const [selectedBookingStep, setSelectedBookingStep] = useState<ItineraryStep | null>(null);
  const [ratings, setRatings] = useState<Record<string, number>>({});
  
  const autoGeneratedRef = useRef<Set<string>>(new Set());
  const mapSources = result.sources.filter(s => s.type === 'map');
  const webSources = result.sources.filter(s => s.type === 'web');
  const t = TRANSLATIONS[preferences.language];

  useEffect(() => {
    if (result.steps && result.steps.length > 0) {
      setSteps(result.steps);
      autoGeneratedRef.current.clear();
      if (result.steps[0].day) setActiveDay(result.steps[0].day);
    } else {
      setSteps([]);
    }
  }, [result]);

  useEffect(() => {
    try {
      const saved = localStorage.getItem('amposta_explorer_ratings');
      if (saved) setRatings(JSON.parse(saved));
    } catch (e) { console.error("Error loading ratings", e); }
  }, []);

  const handleRateStep = (title: string, rating: number) => {
    const newRatings = { ...ratings, [title]: rating };
    setRatings(newRatings);
    localStorage.setItem('amposta_explorer_ratings', JSON.stringify(newRatings));
  };

  const uniqueDays = Array.from(new Set(steps.map(s => s.day)));
  const visibleSteps = steps.filter(step => step.day === activeDay);

  const bookingCandidates = steps.filter((step, index, self) => {
    const lower = step.title.toLowerCase();
    const isGeneric = lower.includes("check-in") || lower.includes("check-out") || lower.length < 4;
    return !isGeneric && index === self.findIndex((t) => t.title === step.title);
  });

  const handleMoveStep = (stepId: string, direction: 'up' | 'down') => {
    const currentIndex = visibleSteps.findIndex(s => s.id === stepId);
    if (currentIndex === -1) return;
    const targetIndex = direction === 'up' ? currentIndex - 1 : currentIndex + 1;
    if (targetIndex < 0 || targetIndex >= visibleSteps.length) return;
    const stepToMove = visibleSteps[currentIndex];
    const stepToSwap = visibleSteps[targetIndex];
    const globalIndex1 = steps.findIndex(s => s.id === stepToMove.id);
    const globalIndex2 = steps.findIndex(s => s.id === stepToSwap.id);

    if (globalIndex1 !== -1 && globalIndex2 !== -1) {
      const newSteps = [...steps];
      [newSteps[globalIndex1], newSteps[globalIndex2]] = [newSteps[globalIndex2], newSteps[globalIndex1]];
      setSteps(newSteps);
    }
  };

  const handleUpdateNotes = (stepId: string, notes: string) => {
    const newSteps = steps.map(s => s.id === stepId ? { ...s, userNotes: notes } : s);
    setSteps(newSteps);
  };

  const handleGenerateImage = async (stepId: string) => {
      const step = steps.find(s => s.id === stepId);
      if (!step) return;
      autoGeneratedRef.current.add(stepId);
      const imageUrl = await generateStepImage(step.title, step.description);
      if (imageUrl) {
          setSteps(currentSteps => currentSteps.map(s => s.id === stepId ? { ...s, imageUrl } : s));
      }
  };

  const handleGenerateInstructions = async (stepId: string) => {
      const step = steps.find(s => s.id === stepId);
      if (!step || step.detailedInstructions) return;
      const instructions = await generateStepInstructions(step.title, step.description, preferences.language);
      if (instructions.length > 0) {
          setSteps(currentSteps => currentSteps.map(s => s.id === stepId ? { ...s, detailedInstructions: instructions } : s));
      }
  };

  const handleFetchNearby = async (stepId: string) => {
      const step = steps.find(s => s.id === stepId);
      if (!step || step.nearbyAttractions) return;
      const nearby = await getNearbyAttractions(step.title, preferences.language);
      if (nearby) {
          setSteps(currentSteps => currentSteps.map(s => s.id === stepId ? { ...s, nearbyAttractions: nearby } : s));
      }
  };

  const isLikelyAttraction = (step: ItineraryStep) => {
     const lowerTitle = step.title.toLowerCase();
     if (lowerTitle.includes('check-in') || lowerTitle.includes('check-out')) return false;
     if (lowerTitle.startsWith('travel to') || lowerTitle.startsWith('viaje a')) return false;
     return true;
  };

  useEffect(() => {
    const generateImagesSequentially = async () => {
        for (const step of steps) {
            if (!step.imageUrl && !autoGeneratedRef.current.has(step.id)) {
                autoGeneratedRef.current.add(step.id);
                await handleGenerateImage(step.id);
                await new Promise(resolve => setTimeout(resolve, 3000));
            }
        }
    };
    generateImagesSequentially();
  }, [steps]);

  const isSpecialEvent = (step: ItineraryStep) => {
     const text = (step.title + step.description).toLowerCase();
     const eventKeywords = ["festa", "festes", "fira", "festival", "jornada", "diada", "concurs", "marató", "cursa", "mercado", "feria", "fiesta", "cavalcada", "procesión", "desfile", "concert", "concierto", "espectacle"];
     return eventKeywords.some(k => text.includes(k));
  };

  const handleSaveClick = () => {
      if (onSave && onSave()) {
          setShowToast({ msg: t.results.saved_success, type: 'success' });
          setTimeout(() => setShowToast(null), 3000);
      }
  };

  const handleShare = async () => {
      const json = JSON.stringify(preferences);
      const encoded = btoa(encodeURIComponent(json));
      const url = `${window.location.origin}${window.location.pathname}?share=${encoded}`;
      
      try {
        if (navigator.share) {
          await navigator.share({ title: t.results.itinerary_title, text: `Amposta Explorer`, url: url });
        } else {
          await navigator.clipboard.writeText(url);
          setShowToast({ msg: t.results.copied, type: 'info' });
          setTimeout(() => setShowToast(null), 2000);
        }
      } catch (err) { console.error(err); }
  };

  const renderRouteButton = () => {
    let mapMode = 'driving';
    if (preferences.transport === Transport.WALKING) mapMode = 'walking';
    else if (preferences.transport === Transport.BUS || preferences.transport === Transport.TRAIN || preferences.transport === Transport.MIX) mapMode = 'transit';
    else if (preferences.transport === Transport.BIKE) mapMode = 'bicycling';

    let locations: string[] = [];
    if (visibleSteps.length > 0) {
        locations = visibleSteps.map(step => {
            let cleanTitle = step.title.replace(/[:()].*$/, '').trim();
            return `${cleanTitle}, Amposta`;
        }).filter((loc, i, arr) => i === 0 || loc !== arr[i-1]);
    }
    if (locations.length === 0) return null;

    let origin = "Amposta, Tarragona"; 
    if (preferences.transport === Transport.RIVER && preferences.includeUpriver) origin = "Embarcadero de Amposta";
    else if (locations.length > 0) { origin = locations[0]; locations = locations.slice(1); }

    const baseUrl = "https://www.google.com/maps/dir/?api=1";
    const fullUrl = `${baseUrl}&origin=${encodeURIComponent(origin)}${locations.length > 0 ? `&destination=${encodeURIComponent(locations[locations.length - 1])}` : ''}${locations.length > 1 ? `&waypoints=${locations.slice(0, -1).map(w => encodeURIComponent(w)).join('|')}` : ''}&travelmode=${mapMode}`;

    return (
      <a href={fullUrl} target="_blank" rel="noopener noreferrer" className="w-full py-4 px-6 bg-slate-50 border border-slate-200 rounded-xl flex items-center justify-between gap-4 text-stone-600 hover:border-teal-400 hover:text-teal-700 hover:bg-teal-50 transition-all shadow-sm group mb-6 print:hidden">
         <div className="flex items-center gap-3">
             <div className="bg-white p-2 rounded-full border border-slate-200 text-teal-600 group-hover:scale-110 transition-transform">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="3 11 22 2 13 21 11 13 3 11"></polygon></svg>
             </div>
             <div className="text-left leading-tight">
                 <span className="block font-bold text-sm">{t.results.suggested_route}</span>
                 <span className="text-xs text-slate-500">{t.results.view_map} Google Maps</span>
             </div>
         </div>
         <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-slate-300 group-hover:text-teal-500"><polyline points="9 18 15 12 9 6"></polyline></svg>
      </a>
    );
  };
  
  const isBookingSource = (url: string) => /thefork|tripadvisor|opentable|reserv|book/.test(url.toLowerCase());
  const getDirectBookingSource = (step: ItineraryStep) => webSources.find(s => (s.title.toLowerCase().includes(step.title.toLowerCase()) || step.title.toLowerCase().includes(s.title.toLowerCase())) && isBookingSource(s.url));

  return (
    <div className="animate-fade-in space-y-6 relative">
      
      {showToast && (
        <div className={`fixed top-20 left-1/2 transform -translate-x-1/2 px-4 py-2 rounded-lg shadow-xl text-sm z-50 animate-fade-in-up flex items-center gap-2 print:hidden ${showToast.type === 'success' ? 'bg-teal-600 text-white' : 'bg-stone-800 text-white'}`}>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6L9 17l-5-5"/></svg>
          {showToast.msg}
        </div>
      )}

      {/* Header Actions - Improved Responsive Layout */}
      <div className="bg-white p-3 sm:p-4 rounded-xl shadow-sm border border-slate-100 flex flex-wrap sm:flex-nowrap justify-between items-center gap-3 sticky top-[4rem] z-20 print:static print:shadow-none print:border-none">
        <div>
            <h2 className="font-bold text-lg sm:text-xl text-stone-800 flex items-center gap-2">
               <span className="text-xl sm:text-2xl">🗺️</span> {t.results.itinerary_title}
            </h2>
            {preferences.startDate && (
                <p className="text-xs text-stone-500 mt-1 ml-8 sm:ml-9">
                    {t.results.scheduled_date}: <span className="font-semibold text-teal-600">{new Date(preferences.startDate).toLocaleDateString(preferences.language)}</span>
                </p>
            )}
        </div>
        
        {/* Mobile Action Bar - Horizontal Scroll on very small screens if needed, mostly wrap */}
        <div className="flex items-center gap-2 w-full sm:w-auto overflow-x-auto no-scrollbar print:hidden">
          {onSave && (
              <button onClick={handleSaveClick} className="flex-1 sm:flex-none text-xs font-bold text-white bg-teal-600 hover:bg-teal-700 px-3 py-2 rounded-lg transition-colors flex items-center justify-center gap-2 whitespace-nowrap shadow-sm">
                 <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z"></path><polyline points="17 21 17 13 7 13 7 21"></polyline><polyline points="7 3 7 8 15 8"></polyline></svg>
                 {t.save_btn}
              </button>
          )}

          <button onClick={handleShare} className="flex-1 sm:flex-none text-xs font-bold text-stone-600 bg-stone-100 hover:bg-stone-200 px-3 py-2 rounded-lg transition-colors flex items-center justify-center gap-2 whitespace-nowrap">
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="18" cy="5" r="3"></circle><circle cx="6" cy="12" r="3"></circle><circle cx="18" cy="19" r="3"></circle><line x1="8.59" y1="13.51" x2="15.42" y2="17.49"></line><line x1="15.41" y1="6.51" x2="8.59" y2="10.49"></line></svg>
            <span className="hidden sm:inline">{t.share_btn}</span>
          </button>
          
          <button onClick={() => window.print()} className="flex-1 sm:flex-none text-xs font-bold text-stone-600 bg-stone-100 hover:bg-red-50 hover:text-red-600 px-3 py-2 rounded-lg transition-colors flex items-center justify-center gap-2 whitespace-nowrap">
             <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
             <span className="hidden sm:inline">{t.pdf_btn}</span>
          </button>

          <button onClick={onReset} className="flex-1 sm:flex-none text-xs font-bold text-teal-600 bg-teal-50 px-3 py-2 rounded-lg transition-colors whitespace-nowrap">
            {t.create_new_btn}
          </button>
        </div>
      </div>

      {/* Main Itinerary Content */}
      <div className="space-y-6">
        {/* Header Graphic */}
        <div className="h-24 sm:h-32 bg-gradient-to-r from-teal-600 to-blue-600 rounded-2xl relative overflow-hidden shadow-sm print:hidden">
             <div className="absolute inset-0 bg-black/10"></div>
             <div className="absolute bottom-4 left-6 text-white font-bold text-2xl drop-shadow-md">Amposta & Delta</div>
        </div>
        
        {steps.length > 0 ? (
            <div className="space-y-6">
                
                {/* Day Selector - Sticky below header actions */}
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 sticky top-[8.5rem] z-10 bg-stone-50/95 backdrop-blur py-2 print:hidden">
                     <div className="flex items-center gap-2 overflow-x-auto pb-1 no-scrollbar w-full">
                         {uniqueDays.map((day) => (
                           <button
                             key={day}
                             onClick={() => setActiveDay(day)}
                             className={`px-4 py-2 rounded-full text-sm font-bold whitespace-nowrap transition-all border ${
                               activeDay === day 
                                 ? 'bg-teal-600 text-white border-teal-600 shadow-md transform scale-105' 
                                 : 'bg-white text-slate-500 border-slate-200 hover:border-teal-300'
                             }`}
                           >
                             {t.results.day} {day}
                           </button>
                         ))}
                     </div>
                </div>

                {renderRouteButton()}

                {/* Print View: All Steps */}
                <div className="space-y-6 animate-fade-in hidden print:block">
                     {steps.map((step, index) => (
                          <ItineraryStepCard 
                              key={`print-${step.id}`} 
                              step={step} 
                              index={index} 
                              totalSteps={steps.length}
                              transport={preferences.transport}
                              theme={preferences.theme}
                              language={preferences.language}
                              onMoveUp={() => {}} 
                              onMoveDown={() => {}}
                              onUpdateNotes={() => {}}
                              onViewBooking={() => setSelectedBookingStep(step)}
                              isSpecialEvent={isSpecialEvent(step)}
                              hasDirectBooking={!!getDirectBookingSource(step)}
                              userRating={ratings[step.title] || 0}
                          />
                     ))}
                </div>

                {/* Interactive View: Visible Steps */}
                <div className="space-y-5 animate-fade-in print:hidden">
                        {visibleSteps.map((step, index) => (
                                <ItineraryStepCard 
                                    key={step.id} 
                                    step={step} 
                                    index={index} 
                                    totalSteps={visibleSteps.length}
                                    transport={preferences.transport}
                                    theme={preferences.theme}
                                    language={preferences.language}
                                    onMoveUp={() => handleMoveStep(step.id, 'up')}
                                    onMoveDown={() => handleMoveStep(step.id, 'down')}
                                    onUpdateNotes={(notes) => handleUpdateNotes(step.id, notes)}
                                    onGenerateImage={handleGenerateImage}
                                    onGenerateInstructions={handleGenerateInstructions}
                                    onViewBooking={() => setSelectedBookingStep(step)}
                                    onFetchNearby={isLikelyAttraction(step) ? () => handleFetchNearby(step.id) : undefined}
                                    isSpecialEvent={isSpecialEvent(step)}
                                    hasDirectBooking={!!getDirectBookingSource(step)}
                                    userRating={ratings[step.title] || 0}
                                    onRate={(r) => handleRateStep(step.title, r)}
                                />
                        ))}
                </div>
            </div>
         ) : (
            <div className="markdown-body prose prose-stone max-w-none bg-white p-6 rounded-xl border border-slate-200">
                <ReactMarkdown>{result.markdown}</ReactMarkdown>
            </div>
         )}
      </div>

      {/* Bookings & Info Sections (Simplified for brevity, keep logic same as before but wrap in container) */}
      <div className="space-y-4 print:hidden">
           {/* Bookings */}
           {bookingCandidates.length > 0 && (
                <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
                    <button onClick={() => setIsBookingsOpen(!isBookingsOpen)} className="w-full flex justify-between items-center p-4 bg-slate-50 hover:bg-slate-100">
                        <span className="font-bold text-stone-800 flex gap-2"><span>🎟️</span> {t.results.bookings_title}</span>
                        <span className="text-slate-400 text-xl">{isBookingsOpen ? '-' : '+'}</span>
                    </button>
                    {isBookingsOpen && (
                        <div className="p-4 divide-y divide-slate-100">
                             {bookingCandidates.map((item, idx) => (
                                 <div key={idx} className="py-2 flex justify-between items-center">
                                     <span className="text-sm font-medium">{item.title}</span>
                                     <button onClick={() => setSelectedBookingStep(item)} className="text-xs bg-teal-50 text-teal-700 px-2 py-1 rounded border border-teal-100">{t.results.view_booking_btn}</button>
                                 </div>
                             ))}
                        </div>
                    )}
                </div>
           )}
           {/* Delta Info */}
           <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
                <button onClick={() => setIsDeltaInfoOpen(!isDeltaInfoOpen)} className="w-full flex justify-between items-center p-4 bg-teal-50 hover:bg-teal-100">
                     <span className="font-bold text-teal-900 flex gap-2"><span>🦩</span> {t.delta_info.title}</span>
                </button>
                {isDeltaInfoOpen && <div className="p-5 prose prose-sm max-w-none"><ReactMarkdown>{t.delta_info.content}</ReactMarkdown></div>}
           </div>
      </div>
      
      {/* Footer Info */}
      <div className="bg-slate-50 rounded-xl p-6 border border-slate-200 print:hidden text-center text-xs text-slate-400">
           {t.results.verify_warning}
      </div>

      {/* Simplified Booking Modal Logic (Keep same structure as before but add fixed positioning fixes) */}
      {selectedBookingStep && (
         <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-0 sm:p-4 bg-black/50 backdrop-blur-sm animate-fade-in print:hidden">
            <div className="bg-white w-full sm:max-w-lg sm:rounded-xl rounded-t-xl max-h-[90vh] flex flex-col animate-fade-in-up">
               <div className="p-4 border-b border-slate-100 flex justify-between items-center bg-slate-50 rounded-t-xl">
                  <h3 className="font-bold text-stone-800 truncate pr-4">{selectedBookingStep.title}</h3>
                  <button onClick={() => setSelectedBookingStep(null)} className="p-2 bg-slate-200 rounded-full hover:bg-slate-300">✕</button>
               </div>
               <div className="p-6 overflow-y-auto space-y-4">
                   <div className="text-sm text-stone-600 prose prose-sm max-w-none"><ReactMarkdown>{selectedBookingStep.description}</ReactMarkdown></div>
                   <a href={`https://www.google.com/search?q=${encodeURIComponent(selectedBookingStep.title + " reservar")}`} target="_blank" rel="noreferrer" className="block w-full text-center py-3 bg-teal-600 text-white font-bold rounded-xl hover:bg-teal-700">{t.results.view_booking_btn} Google</a>
               </div>
            </div>
         </div>
      )}
    </div>
  );
};

export default ResultDisplay;
